#!/usr/bin/python3
import os
import tarfile

wd = os.getcwd()
cur_dir = os.path.dirname(os.path.realpath(__file__))
os.chdir(cur_dir)

files_list = [
    "eyeflow_conf.json",
    "compose.yaml",
    "run_flow.service",
    "run_flow.sh",
    "install_run_flow_service.sh",
    "cloud_sync.py",
    "cloud_sync.service",
    "cloud_sync.timer",
    "install_cloud_sync_service.sh",
    "request_license.py",
    "run_endpoint.sh",
    "start_edge",
    "stop_edge",
    "restart_edge",
    "upgrade_edge",
    "upload_extracts.py",
    "utils.py"
]

pack_name = "./tmp/edge_install.tar.gz"
with tarfile.open(pack_name, "w:gz") as tar:
    for file in files_list:
        tar.add(file)

os.chdir(wd)

print("**install packs uploaded**")
