#!/usr/bin/python3
import os
import tarfile

wd = os.getcwd()
cur_dir = os.path.dirname(os.path.realpath(__file__))
os.chdir(cur_dir)

files_list = [
    "eyeflow_conf.json",
    "eyeflow-background.jpg",
    "compose.yaml",
    "run_flow.service",
    "run_flow.sh",
    "run_flow_monitor.sh",
    "install_run_flow_service.sh",
    "cloud_sync.py",
    "cloud_sync.service",
    "cloud_sync.timer",
    "install_cloud_sync_service.sh",
    "purge_old_files.sh",
    "purge_old_files.service",
    "purge_old_files.timer",
    "install_purge_old_files_service.sh",
    "request_license.py",
    "run_endpoint.sh",
    "start_service",
    "stop_service",
    "start_container",
    "stop_container",
    "restart_service",
    "upgrade_edge",
    "upload_extracts.py",
    "utils.py",
    "download_file_storage",
    "upload_file_storage",
    "upload_part_files"
]

if not os.path.exists("./tmp"):
    os.mkdir("tmp")

pack_name = "./tmp/edge_install.tar.gz"
with tarfile.open(pack_name, "w:gz") as tar:
    for file in files_list:
        tar.add(file)

os.chdir(wd)

print("**install packs generated**")
