#!/usr/bin/python3

"""
SiliconLife Eyeflow

Author: Alex Sobral de Freitas
"""

import os
import sys
import requests
import argparse
import jwt
from pathlib import Path
from eyeflow_sdk.log_obj import CONFIG, log

proxies = {}
if "proxies" in CONFIG:
    proxies = CONFIG["proxies"]

import utils
#----------------------------------------------------------------------------------------------------------------------------------


def check_dependencies(dependencies, packs, pack_names):
    dep_list = []
    for dep in dependencies:
        if dep not in pack_names:
            log.info(f"Need dependency for pack: {dep}")
            dep_list.append({
                "pack_name": dep,
                "pack_id": dependencies[dep]["pack_id"] if "pack_id" in dependencies[dep] else "",
                "version": dependencies[dep]["min"]}
            )
            continue

        dep_ver_min = dependencies[dep]["min"].split(".")
        dep_ver_max = dependencies[dep]["max"].split(".")

        if dep == "edge_sdk_libs" and dep_ver_min[0] == '2':
            dep_ver_min[0] = '24'
            dep_ver_min[1] = '*'
            dep_ver_max[0] = '25'
            dep_ver_max[1] = '*'

        pack_version = packs[pack_names[dep]]["info"]["version"].split(".")
        pack_ver_int = 0
        dep_ver_min_int = 0
        dep_ver_max_int = 0
        for level in range(3):
            if level >= len(dep_ver_min):
                dep_ver_min_int *= 1000
            elif dep_ver_min[level] == "*":
                dep_ver_min_int *= 1000
            else:
                dep_ver_min_int = (dep_ver_min_int * 1000) + int(dep_ver_min[level])

            if level >= len(dep_ver_max):
                dep_ver_max_int = (dep_ver_max_int * 1000) + 999
            elif dep_ver_max[level] == "*":
                dep_ver_max_int = (dep_ver_max_int * 1000) + 999
            else:
                dep_ver_max_int = (dep_ver_max_int * 1000) + int(dep_ver_max[level])

            if level >= len(pack_version):
                pack_ver_int *= 1000
            else:
                pack_ver_int = (pack_ver_int * 1000) + int(pack_version[level])

        # log.info(f"DepVer Min: {dep_ver_min}-{dep_ver_min_int} - DepVer Max: {dep_ver_max}-{dep_ver_max_int} - PackVer: {pack_version}-{pack_ver_int}")
        if pack_ver_int < dep_ver_min_int or pack_ver_int > dep_ver_max_int:
            # log.info(f"Invalid dependency for pack: {dep} - Pack-ver: {packs[pack_names[dep]]['info']['version']} != [Dep-ver Min: {dependencies[dep]['min']} - Max: {dependencies[dep]['max']}]")
            dep_list.append({
                "pack_name": dep,
                "pack_id": dependencies[dep]["pack_id"] if "pack_id" in dependencies[dep] else "",
                "version": dependencies[dep]["min"]}
            )
            break

    return dep_list
#----------------------------------------------------------------------------------------------------------------------------------


def download_pack(pack_name):
    app_info, app_token = utils.get_license()

    arch = utils.get_device_arch()
    os_version = utils.get_os_version()

    pack_folder = CONFIG["file-service"]["temp_folder"]

    try:
        log.info(f'Download pack {pack_name}-{arch}')

        folder_path = Path(pack_folder)
        if not folder_path.is_dir():
            folder_path.mkdir(parents=True, exist_ok=True)

        endpoint = jwt.decode(app_token, options={"verify_signature": False})['endpoint']
        url = f'{endpoint}/pack-name/{pack_name}/arch/{arch}/os/{os_version}/'
        msg_headers = {'Authorization' : f'Bearer {app_token}'}
        payload = {"download_url": True}
        response = requests.get(url, headers=msg_headers, params=payload, proxies=proxies)

        if response.status_code != 200:
            log.error(f'Failing downloading pack {pack_name}: {response.json()}')
            return None, None

        pack_doc = response.json()
        dest_filename = os.path.join(folder_path, pack_doc["filename"])
        utils.download_file(pack_doc["download_url"], dest_filename)
        return pack_doc, dest_filename

    except requests.ConnectionError as error:
        log.error(f'Failing downloading pack: {pack_name}. Connection error: {error}')
        return None, None
    except requests.Timeout as error:
        log.error(f'Failing downloading pack: {pack_name}. Timeout: {error}')
        return None, None
    except Exception as excp:
        log.error(f'Failing downloading pack: {pack_name} - {excp}')
        return None, None
#----------------------------------------------------------------------------------------------------------------------------------


def install_pack(pack_name):
    try:
        pack_doc, pack_filename = download_pack(pack_name)
        if pack_doc is None or pack_filename is None:
            log.error(f"Fail installing pack {pack_name}")
            return False

        retcode, stdout, stderr = utils.install_pack(pack_doc, pack_filename)
        if retcode != 0:
            log.error(f"Fail installing pack {pack_name}")
            sys.exit(1)

        log.info(f"Pack {pack_name} installed successfully: {stdout}")

    except Exception as excp:
        log.error(f'Failing downloading pack: {pack_name} - {excp}')
        return False

    return True
#----------------------------------------------------------------------------------------------------------------------------------


def parse_args(args):
    """ Parse the arguments.
    """
    parser = argparse.ArgumentParser(description='Install a pack in Edge')
    parser.add_argument('pack_name', help='Pack Name', type=str)

    return parser.parse_args(args)
#----------------------------------------------------------------------------------------------------------------------------------


args = parse_args(sys.argv[1:])

app_info, app_token = utils.get_license()
if "edge_id" in app_info:
    log.info(f'Edge ID: {app_info["edge_id"]} - System ID: {app_info.get("device_sn")}')
elif "endpoint_id" in app_info:
    log.info(f'Endpoint ID: {app_info["endpoint_id"]}')

utils.check_license(app_info)
install_pack(args.pack_name)
