#!/usr/bin/python3

import os
import sys
import argparse
import jwt
import requests

from eyeflow_sdk.log_obj import log, CONFIG
import utils

proxies = {}
if "proxies" in CONFIG:
    proxies = CONFIG["proxies"]
# ---------------------------------------------------------------------------------------------------------------------


def upload_file(app_token, app_info, local_filename):
    try:
        endpoint = jwt.decode(app_token, options={"verify_signature": False})['endpoint']
        msg_headers = {'Authorization' : f'Bearer {app_token}'}
        url = f"{endpoint}/file/{app_info['edge_id']}/upload"

        files = {'extract': open(local_filename, 'rb')}
        values = {
            'filename': os.path.basename(local_filename)
        }

        response = requests.post(url, files=files, data=values, headers=msg_headers, proxies=proxies)

        if response.status_code != 201:
            raise Exception(f"Failing upload extract files: {response.json()['error']['message']}")
    except Exception as excp:
        raise Exception(f"An error occurred: {excp}")
#----------------------------------------------------------------------------------------------------------------------------------


def parse_args(args):
    """ Parse the arguments.
    """
    parser = argparse.ArgumentParser(description='Upload file to misc storage')
    parser.add_argument('local_file_path', help='The path of local file to upload', type=str)

    return parser.parse_args(args)
#----------------------------------------------------------------------------------------------------------------------------------


def main(args=None):
    if args is None:
        args = sys.argv[1:]

    args = parse_args(args)
    if not os.path.exists(args.local_file_path):
        log.error(f"File {args.local_file_path} does not exist.")
        return

    if not os.path.isfile(args.local_file_path):
        log.error(f"Path {args.local_file_path} is not a file.")
        return

    app_info, app_token = utils.get_license()

    try:
        upload_file(app_token=app_token, app_info=app_info, local_filename=args.local_file_path)
    except Exception as e:
        log.error(f"An error occurred: {e}")
        return

    log.info(f"File {args.local_file_path} uploaded successfully.")
#----------------------------------------------------------------------------------------------------------------------------------

main()
