#!/usr/bin/python3
import os
import sys
import json
import argparse
import tarfile
import jwt
import requests

from eyeflow_sdk.log_obj import log, CONFIG

import utils
# ---------------------------------------------------------------------------------------------------------------------

proxies = {}
if "proxies" in CONFIG:
    proxies = CONFIG["proxies"]

if "storage_credentials" not in CONFIG:
    log.error("Storage credentials not found in the configuration.")
    exit(1)
# ---------------------------------------------------------------------------------------------------------------------

def upload_files_part(app_token, app_info, folder, date, part):
    try:
        base_folder = "/opt/eyeflow/data/"
        src_folder = os.path.join(base_folder, folder, date)
        tar_filename = f"/tmp/{part}.tar.gz"
        if os.path.isfile(tar_filename):
            os.remove(tar_filename)

        with tarfile.open(tar_filename, "w:gz") as tar:
            wd = os.getcwd()
            os.chdir(src_folder)
            for filename in os.listdir():
                if f"_{part}" in filename:
                    tar.add(os.path.basename(filename))

            os.chdir(wd)

        endpoint = jwt.decode(app_token, options={"verify_signature": False})['endpoint']
        msg_headers = {'Authorization' : f'Bearer {app_token}'}
        url = f"{endpoint}/file/{app_info['edge_id']}/upload"

        files = {'extract': open(tar_filename, 'rb')}
        values = {
            'filename': os.path.basename(tar_filename)
        }

        response = requests.post(url, files=files, data=values, headers=msg_headers, proxies=proxies)

        if response.status_code != 201:
            raise Exception(f"Failing upload extract files: {response.json()['error']['message']}")

        log.info(f"File {tar_filename} uploaded successfully.")

    except Exception as excp:
        log.error(f"An error occurred: {excp}")
# ---------------------------------------------------------------------------------------------------------------------


parser = argparse.ArgumentParser(description='Copy parts files')
parser.add_argument('date', help='A data', type=str)
parser.add_argument('parts_list', help='A lista de ids separada por virgula', type=str)

app_info, app_token = utils.get_license()

args = parser.parse_args(sys.argv[1:])
part_list = args.parts_list.split(',')
for part in part_list:
    upload_files_part(app_token, app_info, "video", args.date, part)
